metadata.json
=> Drop EoL Puppet 4/5 support, Add 7

metadata.json
=> Drop EoL Ubuntu 14/16 support

.fixtures.yml, metadata.json
=> Allow latest module versions

metadata.json
=> Drop EoL Debian 8/9 support, add 10/11

.puppet-lint.rc, .sync.yml, REFERENCE.md, manifests/init.pp
=> Enforce documentation for new parameters

spec/acceptance/class_spec.rb, spec/setup_acceptance_node.pp
=> Add CI job for package based installation

REFERENCE.md, manifests/config.pp, manifests/init.pp, spec/classes/vault_spec.rb
=> Dont create vault config dir for package based installations

manifests/init.pp
=> Update version from 1.4.2->1.12.0

README.md
=> README.md: fix wrong camptocamp references

manifests/init.pp
This was introduced in the transition from params.pp to init.pp
=> Fix Typo in $listener data

manifests/config.pp, manifests/init.pp, manifests/install.pp, spec/classes/vault_spec.rb
Reverts voxpupuli/puppet-vault#7
=> Revert "Support upgrades and consul service registration"

.github/SECURITY.md, .msync.yml, Gemfile, Guardfile
=> Update from voxpupuli modulesync_config

metadata.json
=> Add EL8/9 & Rocky/AlmaLinux/OracleLinux support

CHANGELOG.md, README.md, metadata.json
=> Release 4.0.0

.github/workflows/ci.yml, .sync.yml, spec/spec_helper_acceptance.rb
cleanup for manual changes in spec/spec_helper_acceptance.rb from https://github.com/voxpupuli/puppet-vault/pull/52
=> modulesync 9.1.0

CHANGELOG.md, metadata.json
Release v4.1.1 pending release
Closes #58
=> Release v4.1.1

templates/vault.systemd.erb
This PR follows the baseline guidelines of Hashicorp Vault.
Setting this parameter is recommended for production setups and is hardening the overall infrastructure.
You can find the guideline here:
https://developer.hashicorp.com/vault/docs/concepts/production-hardening#baseline-recommendations
=> Add Systemd Parameter LimitCORE to template

manifests/config.pp
=> Replace legacy merge() with native puppet code

metadata.json
=> Add Ubuntu 22.04 & 24.04 support

metadata.json
=> Drop EoL CentOS 7 & 8

metadata.json
=> Drop EoL RedHat 7

manifests/config.pp, metadata.json
=> Require stdlib 9.x / use namespaced functions

.github/workflows/ci.yml, .sync.yml, REFERENCE.md, manifests/init.pp, spec/acceptance/class_spec.rb
This is the latest stable version Hashicorp offers.
=> Add Vault 1.19.2 to CI
